rvpadman@gmail.com/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Expertise__c</fullName>
        <description>Top level picklist</description>
        <label>Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>ESC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefits</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>GC1040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>401k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

rvpadman@gmail.com/src/classes/SimilarKBCasesExtension.cls
public class SimilarKBCasesExtension {

    public Case currentRecord{get; set;}
    
    public SimilarKBCasesExtension (ApexPages.StandardController controller)
     {
        currentRecord = [SELECT Id, Expertise__c,Product__c,Reason FROM Case WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
    }
  
    public Case[] getSimilarCases()
    {
    
     //   Case currentCase = currentRecord();
        return [SELECT CaseNumber, Status,Product__C,Expertise__C,Reason FROM Case WHERE 
            Product__c = :currentRecord.Product__c AND
            Expertise__c = :currentRecord.Expertise__c AND
            Reason = :currentRecord.Reason AND
            Id != :currentRecord.Id];
    }
   
 }