rvpadman@gmail.com/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Expertise__c</fullName>
        <description>Top level picklist</description>
        <label>Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>ESC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefits</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>GC1040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>401k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

rvpadman@gmail.com/src/classes/SimilarCasesController.cls
public class SimilarCasesController {
public Case getCurrentCase() {
    String cid = ApexPages.currentPage().getParameters().get('cid');
    List<Case> cases = [SELECT Id, CaseNumber, Reason, Product__c, Expertise__c FROM Case WHERE Id = :cid];
    if (cases.size() > 0) 
      {
      return cases.get(0);
      }
      else
      {
      return null;
      }
  //  return cases.size() > 0 ? cases.get(0) : new Case();
    }
public Case[] getSimilarCases() {
Case currentCase = getCurrentCase();
return [SELECT Id, CaseNumber, Owner.Name, Subject, Status FROM Case WHERE 
Product__c = :currentCase.Product__c AND
Expertise__c = :currentCase.Expertise__c AND
Reason = :currentCase.Reason AND
Id != :currentCase.Id];
    }
}