rvpadman@gmail.com/src/objects/Chatter_Up__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Describe the objects that you want to Chatter to parent when they are created.</description>
    <fields>
        <fullName>Chatter_Link_Title__c</fullName>
        <description>The title of the hyperlink to the newly created record.</description>
        <inlineHelpText>This is the title that will be displayed in the link. Leave it blank if you do not wish to see a hyperlink to the newly created record in the Chatter post.</inlineHelpText>
        <label>Chatter Link Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chatter_Post_Body__c</fullName>
        <description>The body of the Chatter post to be created.</description>
        <inlineHelpText>Enter the text that you want to see in the created Chatter post.</inlineHelpText>
        <label>Chatter Post Body</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>The API name of the object that needs Chatter Up.</description>
        <inlineHelpText>Enter the object name. Can be a custom object, or a standard object.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_ID_Field__c</fullName>
        <description>The API name of the field that identifies the parent record.</description>
        <inlineHelpText>The API name of the field that identifies the parent record. This needs to be a relationship field (e.g the AccountID field in the Opportunity record)</inlineHelpText>
        <label>Parent ID Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Chatter Up</label>
</CustomObject>

rvpadman@gmail.com/src/classes/testChatterOpptyOnAccount.cls
@isTest
private class testChatterOpptyOnAccount {
    static testMethod void testChatterOppty() {
        List<Opportunity> myOpportunities = new List<Opportunity>();
        Chatter_Up__c settings = createChatterUpConfig();
        insert settings;
        
        /* Create 1 test account */
        Account a = new Account(name = 'testAccount');
        insert a;
        
        /* Create 100 test opportunities */
        for(Integer i=0; i < 100; i++){
            Opportunity o = new Opportunity(Name = 'TestOpp_'+i);
            o.AccountId = a.id;
            o.CloseDate = date.Today()+i;
            o.StageName = 'Negotiation/Review';
            myOpportunities.add(o);
        }
        
        test.startTest();
        insert myOpportunities;
        test.stopTest();
        
        /*there should be 100 posts as you iterated 100 times*/
        List<AccountFeed> chatterPosts = [select id from AccountFeed where parentId = :a.id];
        System.assertEquals(chatterPosts.size(), 100);

    }
    
    static private Chatter_Up__c createChatterUpConfig() {
    	
    	Chatter_Up__c setting = new Chatter_Up__c();
    	
    	setting.name = 'Opportunity Settings';
    	setting.object_api_name__c = 'Opportunity';
    	setting.parent_id_field__c = 'accountid';
    	setting.chatter_post_body__c = 'This is a test';
    	setting.chatter_link_title__c = 'This is test title';
    	
    	return setting;
    }     
}