rvpadman@gmail.com/src/objects/Chatter_Up__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Describe the objects that you want to Chatter to parent when they are created.</description>
    <fields>
        <fullName>Chatter_Link_Title__c</fullName>
        <description>The title of the hyperlink to the newly created record.</description>
        <inlineHelpText>This is the title that will be displayed in the link. Leave it blank if you do not wish to see a hyperlink to the newly created record in the Chatter post.</inlineHelpText>
        <label>Chatter Link Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chatter_Post_Body__c</fullName>
        <description>The body of the Chatter post to be created.</description>
        <inlineHelpText>Enter the text that you want to see in the created Chatter post.</inlineHelpText>
        <label>Chatter Post Body</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>The API name of the object that needs Chatter Up.</description>
        <inlineHelpText>Enter the object name. Can be a custom object, or a standard object.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_ID_Field__c</fullName>
        <description>The API name of the field that identifies the parent record.</description>
        <inlineHelpText>The API name of the field that identifies the parent record. This needs to be a relationship field (e.g the AccountID field in the Opportunity record)</inlineHelpText>
        <label>Parent ID Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Values__c</fullName>
        <description>The Values that are allowed when Chatter Up is checking the &apos;Picklist That Constrains&apos; field.</description>
        <inlineHelpText>Enter the values that you want to specify when Chatter Up occurs. e.g. For the Priority on a new Case, you could specify &apos;High;Low&apos; (no quotes) to ensure that only High Priority or Low Priority cases Chatter Up.</inlineHelpText>
        <label>Picklist Values</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_that_Constrains_Chatter_Up__c</fullName>
        <description>The API name of the field that Chatter Up will reference when deciding if this particular record will Chatter Up.</description>
        <inlineHelpText>The API name of the field that Chatter Up will reference when deciding if this particular record will Chatter Up. e.g. the Priority field on the Case object</inlineHelpText>
        <label>Picklist that Constrains Chatter Up</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chatter Up</label>
</CustomObject>

rvpadman@gmail.com/src/classes/testChatterCaseOnAccount.cls
@isTest
private class testChatterCaseOnAccount {
	
	
    static testMethod void testChatterCase() {
    	
        List<Case> myCases = new List<Case>();
        Chatter_Up__c setting = createChatterUpConfig();
        insert setting;
 
        /* Create 1 test account */
        Account a = new Account(name = 'testAccount');
        insert a;
        
        /* Query for any BusinessHours record to associate with case, as you cannot perform any DML operations on this object in apex, and this is necessary for cases of specific record types */
        List<BusinessHours> bh = [select Id from BusinessHours limit 1];
        String BusinessHoursId;
        if(bh.size() > 0){
            BusinessHoursId = bh[0].Id;
        }
        /* used to test that the Case Priority constraint is working correctly */
        Integer numberOfHighOrMediumCases = 0;
        
        /* Create 100 test cases */
        
        for(Integer i = 2; i < 102; i++){
            Case c = new Case(priority = 'High', origin = 'Web', Status = 'New');
            c.BusinessHoursId = BusinessHoursId;
            
            /* this will associate every other case to my testAccount */
            if(math.mod(i, 2) == 0){
                c.AccountId = a.id;
            }
            
            myCases.add(c);
        } 
        
        test.startTest();
        insert myCases;
        test.stopTest();
        
        /*there should be 50 posts as you iterated 100 times, and half were associated with an Account and a high priority*/
        List<AccountFeed> chatterPosts = [select id from AccountFeed where parentId = :a.id];
        System.assertEquals(chatterPosts.size(), 50);

    }
    
    static private Chatter_Up__c createChatterUpConfig() {
    	
    	Chatter_Up__c setting = new Chatter_Up__c();
    	
    	setting.name = 'Case Settings';
    	setting.object_api_name__c = 'Case';
    	setting.parent_id_field__c = 'accountid';
    	setting.picklist_that_constrains_chatter_up__c = 'Priority';
    	setting.picklist_values__c = 'High;Medium';
    	setting.chatter_post_body__c = 'This is a test';
    	setting.chatter_link_title__c = 'This is test title';
    	
    	return setting;
    }    	

}